feat: msp chargeable tick is current tick
Moonsong-Labs/storage-hub pull request #234
Opened 2024-10-22 14:41 UTC by undercover-cactus

Last chargeable tick is set by default to be the current tick.

In case of dynamic payment we get the last chargeable info and get the last chargeable tick for it.

2024-10-29 03:32 UTC, ffarall requested changes

2024-10-29 03:32 UTC, ffarall commented on pallets/payment-streams/src/lib.rs
> +    // List of priviledge providers
Using `///` for rust docs makes it easier then to hover over the type where it's used, and see what it is about.

```suggestion
    /// Mapping of Privileged Providers.
    ///
    /// Privileged Providers are those who are allowed to charge up to the current tick in
    /// fixed rate payment streams, regardless of their [`LastChargeableInfo`].
```

2024-10-29 20:41 UTC, snowmead approved these changes
lgtm modulo @ffarall comment about the tests

2024-10-31 15:43 UTC, undercover-cactus commented
I have now a failing test `charge_three_users_with_different_payment_streams_works`. This test is failing because when Alice sign up as a MSP they are registered as Privilege Provider now.

So when a dynamic stream payment is being charged the index price returned is the default value which is 0 and not the value from the ProviderLastChargeableInfo that has been inserted in the test.

2024-11-04 15:19 UTC, ffarall approved these changes

2024-11-05 20:27 UTC, merged