feat: ✨ benchmark payment streams pallet
Moonsong-Labs/storage-hub pull request #254
Opened 2024-11-12 02:18 UTC by TDemeco

In this PR:
- The `ProviderId` type and `ValuePropId` type from the `storage-providers` pallet were refactored to be configurable from the runtime instead of being hardcoded to the hashing type of the runtime. This puts this types in line with other generic hashing types from the rest of the pallets used in StorageHub and allows for more flexibility for other users of it.
- The `pay_outstanding_debt` extrinsics of the `payment-streams` pallet was refactored to not be unbounded. Now, the user has to specifically pass as an argument the maximum amount of payment streams that it wants to pay, and will be charged the according weight. This prevents a possible spam scenario where users could try to gather as much payment streams as possible and call this extrinsic to spam nodes.
  - Note: the previously emitted `UserPaidDebts` event was replaced with two new ones: `UserPaidSomeDebts` which is emitted when there are payment streams remaining after a user calls this extrinsic, and `UserPaidAllDebts` when there are none remaining.
- The `clear_insolvent_flag` extrinsic has also been refactored, now no longer automatically pays remaining payment streams. The user now has to have already called `pay_outstanding_debt` until all its payment streams are paid for before being able to use it.
- The way that the `on_poll` hook is executed was completely changed. Now:
  - Each internal function called in the `on_poll` hook handles charging the weightmeter accordingly, and also fails safely when it can't do it.
  - The main change can be seen in `do_update_last_chargeable_info`. The previous logic did not allow the flexibility of catching back up without missing proof submitters if, for some reason, the `payment-streams` pallet falled behind the `proofs-dealer` and since the `on_poll` hook is not mandatory, this was a possibility that had to be handled. Now, instead of jumping directly to the last tick of submitters, the `payment-streams` pallet slowly catches back up processing each tick between the last processed one and that one, utilizing as much weight as possible to do so.
    - This plus the better handling of remaining weight meant that ticks could get partially processed instead of being a black and white process. Logic was also refactored to have this in mind, allowing the `payment-streams` pallet to resume processing a tick in the next `on_poll` hook call if it ran out of weight in the middle of the process.
- Finally (and probably most importantly), the `payment-streams` pallet was completely benchmarked. There are some extra benchmarks left for which their results are not currently in use; these were done just to make sure we were considering the worst case scenario, as they explore the different pathways of certain function calls.

2024-11-13 21:08 UTC, ffarall requested changes
Stopping review after going through changes in `do_update_last_chargeable_info`. Requesting changes in it, to simplify it and use already existing bound of Proof Submitters.

2024-11-14 21:02 UTC, ffarall approved these changes

2024-11-14 21:53 UTC, TDemeco commented on pallets/payment-streams/src/utils.rs
> +        )?;
To be explored when refactoring `pay_outstanding_debt` 👍🏻

2024-11-14 21:53 UTC, TDemeco commented on pallets/payment-streams/src/benchmarking.rs
> +    fn charge_multiple_users_payment_streams() -> Result<(), BenchmarkError> {
Done!

2024-11-15 16:02 UTC, merged